name: hello_world
on: [push]
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            -   name: create_hello
                run: |
                    touch hello.txt
                    ls -l

            
