name: hello-world
on: [push]
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            name: create-hello
            run: |
                touch hello.txt
                ls -l
    
            
